# The amount it will cost to create a town.
creation_cost: 1000

# The period for which upkeep & taxes will be charged for each town as well as tax collected from residents in each town (in hours). Valid values: (0, 672]
period:
  upkeep: 72
  tax: 72
  # Time (in minutes) that the server will check up on upkeep timers. Values less than 5 not recommended, has minimal performance impact.
  checkup: 5

# Border Colors: What color should the borders be to other towns given relation?
border:
  self:
    # Height may be between 1-5
    height: 3
    # Colors are RGB as hexidecimal
    color: 0x00FF00
  friendly:
    height: 1
    color: 0x008080
  neutral:
    height: 1
    color: 0xFFFF00
  hostile:
    height: 3
    color: 0xFF0000


# cost = flat rate + cost per plot (amount of plots - maximum plots of previous tier)

title:
  # Title from hamlet to major city of town leader
  city: 'Mayor'
  # Title for leader of city state
  state: 'Governor'

# Info for each tier of towns
town_tiers:
  hamlet:
    # How much should the user pay when claiming a plot as this town type?
    claim_fee: 4.0
    # Maximum amount of plots to be considered this tier of town
    max_plots: 8
    upkeep:
      # A flat rate always added to the total upkeep cost
      flat_rate: 50.0
      # How much each plot should cost above the threshold. (Always will be at least one counted at this rate.)
      plot_cost: 2

  village:
    # How much should the user pay when claiming a plot as this town type?
    claim_fee: 5.0
    # Maximum amount of plots to be considered this tier of town
    max_plots: 16
    upkeep:
      # A flat rate always added to the total upkeep cost
      flat_rate: 70.0
      # How much each plot should cost above the threshold. (Always will be at least one counted at this rate.)
      plot_cost: 2.5
  town:
    # How much should the user pay when claiming a plot as this town type?
    claim_fee: 8.0
    # Maximum amount of plots to be considered this tier of town
    max_plots: 32
    upkeep:
      # A flat rate always added to the total upkeep cost
      flat_rate: 100.0
      # How much each plot should cost above the threshold. (Always will be at least one counted at this rate.)
      plot_cost: 4.0
  city:
    # How much should the user pay when claiming a plot as this town type?
    claim_fee: 10.0
    # Maximum amount of plots to be considered this tier of town
    max_plots: 64
    upkeep:
      # A flat rate always added to the total upkeep cost
      flat_rate: 180.0
      # How much each plot should cost above the threshold. (Always will be at least one counted at this rate.)
      plot_cost: 5.0
  major_city:
    # How much should the user pay when claiming a plot as this town type?
    claim_fee: 15.0
    # Maximum amount of plots to be considered this tier of town
    max_plots: 128
    upkeep:
      # A flat rate always added to the total upkeep cost
      flat_rate: 400.0
      # How much each plot should cost above the threshold. (Always will be at least one counted at this rate.)
      plot_cost: 7.5
  city_state:
    # How much should the user pay when claiming a plot as this town type?
    claim_fee: 20.0
    # City states have no maximum amount of plots as they are very expensive to upkeep. You may set a maximum plot amount
    max_plots: -1
    upkeep:
      # A flat rate always added to the total upkeep cost
      flat_rate: 700.0
      # How much each plot should cost above the threshold. (Always will be at least one counted at this rate.)
      plot_cost: 10.0